proc GenerateStairCase(float $stairHight,float $stairDepth,float $stairWidth,int $indacatedStepnumber,float $yOffSet,float $pivotX,float $pivotY,float $pivotZ)
{
 /////////// Values /////////////

    float $stairYvalue = $stairHight;

    int $stiarnumber;

    float $offcenter;
 

    while($indacatedStepnumber > $stiarnumber)
    {

    string $steps[] = `polyCube -height $stairHight -width $stairWidth -depth $stairDepth -n "steps"`;

    $offcenter = $stairWidth / 2;

    move $offcenter ($stairYvalue + $stiarnumber) 0;

    rotate -y ($yOffSet * $stiarnumber) -pivot $pivotX $pivotY $pivotZ -componentSpace;

    $stiarnumber++;

    }
}

//  (stairHight, stairDepth, stairWidth, indacatedStepnumber, yOffSet, pivotX, pivotY, pivotZ)
GenerateStairCase(2,2,8,24,13,0,0,0);